### ISSUE TITLE
Add Instructions on how to run the program

### ISSUE THREAD

**Issue by stoulram** [Leo40Git/super-lesbian-textbox-generator#1]
I see that there's a `start.bat` file but when I double click on it, it immediately opens and closes a window. 
Are there any other instructions needed to follow to run it? It would be helpful if this was listed in the README.md

**Comment by Leo40Git** [comment]
The instructions are "Run the `start.bat` file", which is what you're doing.

Please upload the `app.log` file (it's supposed to appear in the same directory as the `start.bat` file).

**Comment by stoulram** [comment]
> The instructions are "Run the `start.bat` file", which is what you're doing.
> 
> Please upload the `app.log` file (it's supposed to appear in the same directory as the `start.bat` file).

Hmm..I don't see an `app.log` after trying to run it. I tried running it normally and with admin privileges but it still only shows the window briefly. Here's a gif of how it looks on my end:
![ezgif-2-9fa9927004](https://user-images.githubusercontent.com/124744661/219882931-732ae11e-5899-4d7a-9f6b-6b693a3d48bc.gif)

**Comment by Leo40Git** [comment]
Interesting... are you sure you have Java 17 installed? The fact that its not starting _at all_ means this is somewhat out of my control.

Try replacing the contents of `start.bat` with this, it'll pause for a keypress before closing:
```bat
@echo off
pushd %~dp0
call bin/app.bat
popd
pause
```

**Comment by stoulram** [comment]
Here let me upload a better gif of it actually:
![ezgif-2-a6fbac2b73](https://user-images.githubusercontent.com/124744661/219883132-d09ab573-2174-46fa-9283-86aa7ff03a0c.gif)

I think you might be right in that I need to setup my JAVA_HOME path correctly bc when I paused on one frame it was showing that as an error.

**Comment by stoulram** [comment]
Here it is with the command edited in `start.bat`
<img width="675" alt="image" src="https://user-images.githubusercontent.com/124744661/219883205-e2cc9837-1f4f-45c5-91df-50956991666b.png">

I'll try to set up java properly on my end and report back if it fixed it.

**Comment by stoulram** [comment]
Ok yeah I installed openjdk17 and now can confirm that it works :). You can close the issue now.
<img width="309" alt="image" src="https://user-images.githubusercontent.com/124744661/219883392-7ab6e609-7345-4c55-bd35-8f518ac3ac68.png">
![melody](https://user-images.githubusercontent.com/124744661/219883397-29735021-6d76-4115-944b-b17915943103.png)

**Comment by Leo40Git** [comment]
👍
This will not be needed for the full release, FYI.
