### ISSUE TITLE
Program fails to run

### ISSUE THREAD

**Issue by HokoraYinphineMPP** [Leo40Git/super-lesbian-textbox-generator#2]
# Issue 
Both shared and self built jar file does not run.
# Machine
`Windows 10 Home 21H1 19043.2364`

`openjdk 17.0.7 2023-04-18 LTS`
`OpenJDK Runtime Environment Zulu17.42+19-CA (build 17.0.7+7-LTS)`
`OpenJDK 64-Bit Server VM Zulu17.42+19-CA (build 17.0.7+7-LTS, mixed mode, sharing)`

Toolchains: 
`Oracle JRE 1.8.0_351-b10`
`Zulu JDK 11.0.19+7-LTS`
`Zulu JDK 17.0.7+7-LTS`
# Screenshots/Videos
https://github.com/Leo40Git/super-lesbian-textbox-generator/assets/54823358/aea0d9b6-58c8-43ee-9202-71fb9f145d1f

**Comment by Leo40Git** [comment]
Yeah sorry, this app isn't even close to being operational yet
